version: "3"

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: rocketpay
      POSTGRES_PASSWORD: secret
    ports:
      - 54322:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
